function trc_data = three_color_trace_dat_reader(filename)
    opts = detectImportOptions(filename);
    opts.VariableNames = {'time', 'fret01', 'fret02', 'fret12', ...
        'ex0em0', 'ex0em1', 'ex0em2', ...
        'ex1em0', 'ex1em1', 'ex1em2', ...
        'ex2em0', 'ex2em1', 'ex2em2', ...
        'ex0em0_raw', 'ex0em1_raw', 'ex0em2_raw', ...
        'ex1em0_raw', 'ex1em1_raw', 'ex1em2_raw', ...
        'ex2em0_raw', 'ex2em1_raw', 'ex2em2_raw',};
    trc_data = readtable(filename, opts);
end